// Banco de Dados Central Scout Analytics 2026
// Dados estruturados e revisados com métricas avançadas para o Dashboard

export const playersInfo = [
  { id: 'neymar', name: 'Neymar', color: '#ef4444' },
  { id: 'vini', name: 'Vini Jr', color: '#3b82f6' },
  { id: 'raphinha', name: 'Raphinha', color: '#22c55e' },
  { id: 'estevao', name: 'Estêvão', color: '#a855f7' },
  { id: 'joaopedro', name: 'João Pedro', color: '#f59e0b' },
  { id: 'rodrygo', name: 'Rodrygo', color: '#ffffff' },
  { id: 'richarlison', name: 'Richarlison', color: '#64748b' },
  { id: 'jesus', name: 'G. Jesus', color: '#0ea5e9' },
  { id: 'martinelli', name: 'Martinelli', color: '#ec4899' },
  { id: 'cunha', name: 'M. Cunha', color: '#8b5cf6' },
  { id: 'thiago', name: 'Igor Thiago', color: '#14b8a6' },
  { id: 'paqueta', name: 'Paquetá', color: '#f97316' },
  { id: 'henrique', name: 'L. Henrique', color: '#84cc16' },
  { id: 'endrick', name: 'Endrick', color: '#06b6d4' },
];

const createEmptyStats = () => ({ 
  gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, 
  xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 
});

export const evolutionData = [
  {
    year: '2018',
    clubes: {
      neymar: { gols: 23, assist: 13, ga: 36, mins: 2550, jogos: 28, xg: 17, xa: 10, chancesCriadas: 75, driblesCertos: 110, passesProgressivos: 220, disponibilidade: 50 },
      vini: { gols: 4, assist: 9, ga: 13, mins: 2050, jogos: 31, xg: 5.5, xa: 4.8, chancesCriadas: 35, driblesCertos: 90, passesProgressivos: 100, disponibilidade: 65 },
      raphinha: { gols: 6, assist: 6, ga: 12, mins: 2400, jogos: 43, xg: 5, xa: 5, chancesCriadas: 55, driblesCertos: 90, passesProgressivos: 150, disponibilidade: 92 },
      rodrygo: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      richarlison: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      paqueta: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      joaopedro: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      endrick: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      henrique: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
    },
    selecao: {
      neymar: { gols: 4, assist: 2, ga: 6, mins: 600, jogos: 7, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      vini: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      raphinha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      rodrygo: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      richarlison: { gols: 1, assist: 0, ga: 1, mins: 300, jogos: 4, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 5, assist: 2, ga: 7, mins: 750, jogos: 10, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      paqueta: { gols: 2, assist: 2, ga: 4, mins: 750, jogos: 11, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      joaopedro: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      endrick: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      henrique: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
    },
  },
  {
    year: '2019',
    clubes: {
      neymar: { gols: 19, assist: 12, ga: 31, mins: 2500, jogos: 27, xg: 15, xa: 10, chancesCriadas: 80, driblesCertos: 130, passesProgressivos: 230, disponibilidade: 70 },
      vini: { gols: 6, assist: 3, ga: 9, mins: 2550, jogos: 38, xg: 7, xa: 3.5, chancesCriadas: 40, driblesCertos: 110, passesProgressivos: 160, disponibilidade: 92 },
      raphinha: { gols: 8, assist: 7, ga: 15, mins: 2100, jogos: 32, xg: 6.5, xa: 5.5, chancesCriadas: 50, driblesCertos: 110, passesProgressivos: 160, disponibilidade: 87 },
      rodrygo: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      richarlison: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      paqueta: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      joaopedro: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      endrick: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      henrique: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
    },
    selecao: {
      neymar: { gols: 2, assist: 1, ga: 3, mins: 420, jogos: 5, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      vini: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 1, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      raphinha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      rodrygo: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      richarlison: { gols: 2, assist: 1, ga: 3, mins: 0, jogos: 8, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 3, assist: 2, ga: 5, mins: 0, jogos: 8, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      paqueta: { gols: 0, assist: 0, ga: 0, mins: 100, jogos: 2, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      joaopedro: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      endrick: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      henrique: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
    },
  },
  {
    year: '2020',
    clubes: {
      neymar: { gols: 17, assist: 11, ga: 28, mins: 2850, jogos: 31, xg: 13, xa: 10, chancesCriadas: 85, driblesCertos: 140, passesProgressivos: 270, disponibilidade: 65 },
      vini: { gols: 6, assist: 4, ga: 10, mins: 2900, jogos: 49, xg: 7, xa: 5, chancesCriadas: 55, driblesCertos: 150, passesProgressivos: 220, disponibilidade: 93 },
      raphinha: { gols: 7, assist: 10, ga: 17, mins: 2550, jogos: 32, xg: 7, xa: 7.5, chancesCriadas: 65, driblesCertos: 95, passesProgressivos: 180, disponibilidade: 85 },
      rodrygo: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      richarlison: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      paqueta: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      joaopedro: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      endrick: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      henrique: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
    },
    selecao: {
      neymar: { gols: 8, assist: 4, ga: 12, mins: 0, jogos: 10, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      vini: { gols: 0, assist: 1, ga: 1, mins: 180, jogos: 3, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      raphinha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      rodrygo: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      richarlison: { gols: 5, assist: 2, ga: 7, mins: 800, jogos: 10, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 1, assist: 2, ga: 3, mins: 0, jogos: 8, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      paqueta: { gols: 2, assist: 2, ga: 4, mins: 0, jogos: 10, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      joaopedro: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      endrick: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      henrique: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
    },
  },
  {
    year: '2021',
    clubes: {
      neymar: { gols: 13, assist: 8, ga: 21, mins: 2300, jogos: 28, xg: 11, xa: 8, chancesCriadas: 75, driblesCertos: 120, passesProgressivos: 220, disponibilidade: 55 },
      vini: { gols: 22, assist: 16, ga: 38, mins: 3900, jogos: 52, xg: 16, xa: 13, chancesCriadas: 90, driblesCertos: 210, passesProgressivos: 310, disponibilidade: 96 },
      raphinha: { gols: 11, assist: 3, ga: 14, mins: 3000, jogos: 36, xg: 9.5, xa: 5, chancesCriadas: 75, driblesCertos: 120, passesProgressivos: 200, disponibilidade: 94 },
      rodrygo: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      richarlison: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      paqueta: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      joaopedro: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      endrick: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      henrique: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
    },
    selecao: {
      neymar: { gols: 7, assist: 3, ga: 10, mins: 0, jogos: 8, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      vini: { gols: 3, assist: 3, ga: 6, mins: 0, jogos: 10, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      raphinha: { gols: 2, assist: 5, ga: 7, mins: 0, jogos: 11, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      rodrygo: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      richarlison: { gols: 7, assist: 1, ga: 8, mins: 0, jogos: 11, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 3, assist: 1, ga: 4, mins: 0, jogos: 10, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 3, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      paqueta: { gols: 4, assist: 3, ga: 7, mins: 0, jogos: 16, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      joaopedro: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      endrick: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      henrique: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
    },
  },
  {
    year: '2022',
    clubes: {
      neymar: { gols: 18, assist: 17, ga: 35, mins: 2100, jogos: 29, xg: 14, xa: 12, chancesCriadas: 95, driblesCertos: 130, passesProgressivos: 240, disponibilidade: 55 },
      vini: { gols: 23, assist: 21, ga: 44, mins: 4100, jogos: 55, xg: 18, xa: 16, chancesCriadas: 105, driblesCertos: 230, passesProgressivos: 330, disponibilidade: 95 },
      raphinha: { gols: 10, assist: 12, ga: 22, mins: 3400, jogos: 50, xg: 8, xa: 9.5, chancesCriadas: 95, driblesCertos: 110, passesProgressivos: 240, disponibilidade: 95 },
      rodrygo: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      richarlison: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      paqueta: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      joaopedro: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      endrick: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      henrique: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
    },
    selecao: {
      neymar: { gols: 1, assist: 0, ga: 1, mins: 0, jogos: 3, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      vini: { gols: 1, assist: 1, ga: 2, mins: 320, jogos: 4, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      raphinha: { gols: 2, assist: 2, ga: 4, mins: 480, jogos: 6, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      rodrygo: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      richarlison: { gols: 0, assist: 0, ga: 0, mins: 180, jogos: 3, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 1, assist: 0, ga: 1, mins: 300, jogos: 4, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: { gols: 2, assist: 1, ga: 3, mins: 0, jogos: 6, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 0, assist: 0, ga: 0, mins: 100, jogos: 2, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      paqueta: { gols: 2, assist: 2, ga: 4, mins: 550, jogos: 8, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      joaopedro: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      endrick: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      henrique: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
    },
  },
  {
    year: '2023',
    clubes: {
      neymar: { gols: 1, assist: 3, ga: 4, mins: 400, jogos: 7, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 12 },
      vini: { gols: 24, assist: 11, ga: 35, mins: 3100, jogos: 39, xg: 19, xa: 9, chancesCriadas: 85, driblesCertos: 180, passesProgressivos: 280, disponibilidade: 78 },
      raphinha: { gols: 10, assist: 11, ga: 21, mins: 2800, jogos: 37, xg: 9, xa: 9, chancesCriadas: 85, driblesCertos: 100, passesProgressivos: 220, disponibilidade: 82 },
      rodrygo: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      richarlison: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      paqueta: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      joaopedro: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      endrick: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      henrique: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
    },
    selecao: {
      neymar: { gols: 1, assist: 0, ga: 1, mins: 0, jogos: 2, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      vini: { gols: 2, assist: 2, ga: 4, mins: 0, jogos: 8, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      raphinha: { gols: 4, assist: 4, ga: 8, mins: 0, jogos: 11, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      rodrygo: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      richarlison: { gols: 2, assist: 1, ga: 3, mins: 0, jogos: 6, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 0, assist: 0, ga: 0, mins: 150, jogos: 3, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: { gols: 1, assist: 0, ga: 1, mins: 300, jogos: 5, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 0, assist: 0, ga: 0, mins: 250, jogos: 4, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      paqueta: { gols: 2, assist: 2, ga: 4, mins: 650, jogos: 10, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      joaopedro: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      endrick: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      henrique: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
    },
  },
  {
    year: '2024',
    clubes: {
      neymar: { gols: 3, assist: 1, ga: 4, mins: 700, jogos: 10, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 25 },
      vini: { gols: 22, assist: 11, ga: 33, mins: 3500, jogos: 43, xg: 18, xa: 10, chancesCriadas: 90, driblesCertos: 180, passesProgressivos: 300, disponibilidade: 87 },
      raphinha: { gols: 34, assist: 22, ga: 56, mins: 4500, jogos: 57, xg: 28, xa: 17, chancesCriadas: 130, driblesCertos: 150, passesProgressivos: 330, disponibilidade: 98 },
      rodrygo: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      richarlison: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      paqueta: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      joaopedro: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      endrick: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      henrique: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
    },
    selecao: {
      neymar: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      vini: { gols: 2, assist: 1, ga: 3, mins: 480, jogos: 6, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      raphinha: { gols: 6, assist: 3, ga: 9, mins: 0, jogos: 10, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      rodrygo: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      richarlison: { gols: 2, assist: 1, ga: 3, mins: 550, jogos: 8, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 4, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 1, assist: 1, ga: 2, mins: 0, jogos: 6, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      paqueta: { gols: 2, assist: 2, ga: 4, mins: 700, jogos: 10, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      joaopedro: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      endrick: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      henrique: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
    },
  },
  {
    year: '2025/26',
    clubes: {
      neymar: { gols: 6, assist: 3, ga: 9, mins: 1400, jogos: 24, xg: 0.0, xa: 0.0, chancesCriadas: 30, driblesCertos: 50, passesProgressivos: 80, disponibilidade: 40 },
      vini: { gols: 18, assist: 13, ga: 31, mins: 5893, jogos: 46, xg: 14, xa: 9, chancesCriadas: 70, driblesCertos: 140, passesProgressivos: 230, disponibilidade: 93 },
      raphinha: { gols: 0, assist: 0, ga: 22, mins: 1900, jogos: 26, xg: 11, xa: 5, chancesCriadas: 50, driblesCertos: 60, passesProgressivos: 150, disponibilidade: 70 },
      rodrygo: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      richarlison: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      paqueta: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      joaopedro: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      endrick: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      henrique: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
    },
    selecao: {
      neymar: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      vini: { gols: 3, assist: 2, ga: 5, mins: 0, jogos: 6, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      raphinha: { gols: 3, assist: 2, ga: 5, mins: 0, jogos: 6, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      rodrygo: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      richarlison: { gols: 1, assist: 1, ga: 2, mins: 250, jogos: 4, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: { gols: 0, assist: 0, ga: 0, mins: 180, jogos: 3, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 0, assist: 0, ga: 0, mins: 280, jogos: 4, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      paqueta: { gols: 1, assist: 1, ga: 2, mins: 280, jogos: 4, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      joaopedro: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      endrick: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      henrique: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0.0, xa: 0.0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
    },
  },
];

export const matchHistory = [
  {
    id: 1,
    date: 'Julho de 2019',
    opponent: 'Peru/Argentina',
    score: 'Brasil Campeão',
    importance: 'Máxima (Copa América)',
    neymarPlayed: false,
    dataAnalysis: 'Brasil mostrou eficiência tática total sem Neymar. O coletivo engoliu o individual.'
  },
  {
    id: 2,
    date: 'Março de 2024',
    opponent: 'Inglaterra',
    score: 'Brasil 1 x 0 Inglaterra',
    importance: 'Alta (Wembley)',
    neymarPlayed: false,
    dataAnalysis: 'Jogo marcante do Endrick. xG alto (1.95) provando muita criação de chance sem precisar de um camisa 10 clássico segurando a bola.'
  }
];
