// Banco de Dados Central Scout Analytics 2026
// Dados extraidos de FBref, Transfermarkt, Sofascore, StatMuse e fontes oficiais de clubes.

export const playersInfo = [
  { id: 'neymar', name: 'Neymar', color: '#ef4444' },
  { id: 'vini', name: 'Vini Jr', color: '#3b82f6' },
  { id: 'raphinha', name: 'Raphinha', color: '#22c55e' },
  { id: 'estevao', name: 'Estêvão', color: '#a855f7' },
  { id: 'joaopedro', name: 'João Pedro', color: '#f59e0b' },
  { id: 'rodrygo', name: 'Rodrygo', color: '#e2e8f0' },
  { id: 'richarlison', name: 'Richarlison', color: '#64748b' },
  { id: 'jesus', name: 'G. Jesus', color: '#0ea5e9' },
  { id: 'martinelli', name: 'Martinelli', color: '#ec4899' },
  { id: 'cunha', name: 'M. Cunha', color: '#8b5cf6' },
  { id: 'thiago', name: 'Igor Thiago', color: '#14b8a6' },
  { id: 'paqueta', name: 'Paquetá', color: '#f97316' },
  { id: 'henrique', name: 'L. Henrique', color: '#84cc16' },
  { id: 'endrick', name: 'Endrick', color: '#06b6d4' },
];

const createEmptyStats = () => ({
  gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0,
  xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0
});

export const evolutionData = [
  {
    year: '2018/19',
    clubes: {
      neymar: { gols: 23, assist: 13, ga: 36, mins: 2550, jogos: 28, xg: 17, xa: 10, chancesCriadas: 75, driblesCertos: 110, passesProgressivos: 220, disponibilidade: 50 },
      vini: { gols: 4, assist: 9, ga: 13, mins: 2050, jogos: 31, xg: 5.5, xa: 4.8, chancesCriadas: 35, driblesCertos: 90, passesProgressivos: 100, disponibilidade: 65 },
      raphinha: { gols: 6, assist: 6, ga: 12, mins: 2400, jogos: 43, xg: 5, xa: 5, chancesCriadas: 55, driblesCertos: 90, passesProgressivos: 150, disponibilidade: 92 },
      estevao: createEmptyStats(),
      joaopedro: createEmptyStats(),
      rodrygo: createEmptyStats(),
      richarlison: { gols: 14, assist: 2, ga: 16, mins: 3100, jogos: 35, xg: 11, xa: 2.5, chancesCriadas: 35, driblesCertos: 55, passesProgressivos: 90, disponibilidade: 95 },
      jesus: { gols: 21, assist: 6, ga: 27, mins: 2000, jogos: 41, xg: 21, xa: 5, chancesCriadas: 40, driblesCertos: 50, passesProgressivos: 120, disponibilidade: 93 },
      martinelli: { gols: 10, assist: 0, ga: 10, mins: 0, jogos: 34, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 95 },
      cunha: { gols: 5, assist: 2, ga: 7, mins: 1400, jogos: 29, xg: 5, xa: 2, chancesCriadas: 20, driblesCertos: 30, passesProgressivos: 60, disponibilidade: 75 },
      thiago: createEmptyStats(),
      paqueta: { gols: 1, assist: 0, ga: 1, mins: 1150, jogos: 17, xg: 1.5, xa: 1, chancesCriadas: 15, driblesCertos: 15, passesProgressivos: 90, disponibilidade: 85 },
      henrique: createEmptyStats(),
      endrick: createEmptyStats(),
    },
    selecao: {
      neymar: { gols: 4, assist: 2, ga: 6, mins: 600, jogos: 7, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      vini: createEmptyStats(),
      raphinha: createEmptyStats(),
      estevao: createEmptyStats(),
      joaopedro: createEmptyStats(),
      rodrygo: createEmptyStats(),
      richarlison: { gols: 1, assist: 0, ga: 1, mins: 300, jogos: 4, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 5, assist: 2, ga: 7, mins: 750, jogos: 10, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: createEmptyStats(),
      cunha: createEmptyStats(),
      thiago: createEmptyStats(),
      paqueta: { gols: 2, assist: 2, ga: 4, mins: 750, jogos: 11, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      henrique: createEmptyStats(),
      endrick: createEmptyStats(),
    },
  },
  {
    year: '2019/20',
    clubes: {
      neymar: { gols: 19, assist: 12, ga: 31, mins: 2500, jogos: 27, xg: 15, xa: 10, chancesCriadas: 80, driblesCertos: 130, passesProgressivos: 230, disponibilidade: 70 },
      vini: { gols: 6, assist: 3, ga: 9, mins: 2550, jogos: 38, xg: 7, xa: 3.5, chancesCriadas: 40, driblesCertos: 110, passesProgressivos: 160, disponibilidade: 92 },
      raphinha: { gols: 8, assist: 7, ga: 15, mins: 2100, jogos: 32, xg: 6.5, xa: 5.5, chancesCriadas: 50, driblesCertos: 110, passesProgressivos: 160, disponibilidade: 87 },
      estevao: createEmptyStats(),
      joaopedro: { gols: 10, assist: 4, ga: 14, mins: 2190, jogos: 42, xg: 0.5, xa: 0.1, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 80 },
      rodrygo: createEmptyStats(),
      richarlison: { gols: 15, assist: 3, ga: 18, mins: 3000, jogos: 36, xg: 11, xa: 3, chancesCriadas: 40, driblesCertos: 50, passesProgressivos: 100, disponibilidade: 95 },
      jesus: { gols: 23, assist: 7, ga: 30, mins: 2700, jogos: 47, xg: 18, xa: 6, chancesCriadas: 50, driblesCertos: 60, passesProgressivos: 140, disponibilidade: 95 },
      martinelli: { gols: 10, assist: 0, ga: 10, mins: 1300, jogos: 26, xg: 7, xa: 1, chancesCriadas: 15, driblesCertos: 30, passesProgressivos: 70, disponibilidade: 85 },
      cunha: { gols: 6, assist: 0, ga: 6, mins: 1500, jogos: 28, xg: 5, xa: 2.5, chancesCriadas: 18, driblesCertos: 25, passesProgressivos: 55, disponibilidade: 80 },
      thiago: { gols: 3, assist: 0, ga: 3, mins: 1200, jogos: 27, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 55 },
      paqueta: { gols: 0, assist: 0, ga: 0, mins: 1400, jogos: 27, xg: 1, xa: 0.9, chancesCriadas: 15, driblesCertos: 15, passesProgressivos: 100, disponibilidade: 80 },
      henrique: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 2, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 20 },
      endrick: createEmptyStats(),
    },
    selecao: {
      neymar: { gols: 2, assist: 1, ga: 3, mins: 420, jogos: 5, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      vini: { gols: 0, assist: 0, ga: 0, mins: 30, jogos: 1, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      raphinha: createEmptyStats(),
      estevao: createEmptyStats(),
      joaopedro: createEmptyStats(),
      rodrygo: createEmptyStats(),
      richarlison: { gols: 2, assist: 1, ga: 3, mins: 600, jogos: 8, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 3, assist: 2, ga: 5, mins: 600, jogos: 8, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: createEmptyStats(),
      cunha: createEmptyStats(),
      thiago: createEmptyStats(),
      paqueta: { gols: 0, assist: 0, ga: 0, mins: 100, jogos: 2, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      henrique: createEmptyStats(),
      endrick: createEmptyStats(),
    },
  },
  {
    year: '2020/21',
    clubes: {
      neymar: { gols: 17, assist: 11, ga: 28, mins: 2850, jogos: 31, xg: 13, xa: 10, chancesCriadas: 85, driblesCertos: 140, passesProgressivos: 270, disponibilidade: 65 },
      vini: { gols: 6, assist: 4, ga: 10, mins: 2900, jogos: 49, xg: 7, xa: 5, chancesCriadas: 55, driblesCertos: 150, passesProgressivos: 220, disponibilidade: 93 },
      raphinha: { gols: 7, assist: 10, ga: 17, mins: 2550, jogos: 32, xg: 7, xa: 7.5, chancesCriadas: 65, driblesCertos: 95, passesProgressivos: 180, disponibilidade: 85 },
      estevao: createEmptyStats(),
      joaopedro: { gols: 9, assist: 2, ga: 11, mins: 2800, jogos: 40, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 95 },
      rodrygo: createEmptyStats(),
      richarlison: { gols: 8, assist: 4, ga: 12, mins: 2900, jogos: 37, xg: 9, xa: 4, chancesCriadas: 45, driblesCertos: 45, passesProgressivos: 110, disponibilidade: 95 },
      jesus: { gols: 14, assist: 10, ga: 24, mins: 2400, jogos: 41, xg: 11, xa: 8, chancesCriadas: 65, driblesCertos: 55, passesProgressivos: 180, disponibilidade: 90 },
      martinelli: { gols: 2, assist: 0, ga: 2, mins: 600, jogos: 22, xg: 2, xa: 1, chancesCriadas: 10, driblesCertos: 15, passesProgressivos: 40, disponibilidade: 45 },
      cunha: { gols: 8, assist: 3, ga: 11, mins: 2100, jogos: 30, xg: 7, xa: 3, chancesCriadas: 30, driblesCertos: 40, passesProgressivos: 80, disponibilidade: 85 },
      thiago: { gols: 4, assist: 1, ga: 5, mins: 1800, jogos: 29, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 70 },
      paqueta: { gols: 10, assist: 3, ga: 13, mins: 2500, jogos: 34, xg: 7.5, xa: 4.5, chancesCriadas: 45, driblesCertos: 45, passesProgressivos: 150, disponibilidade: 90 },
      henrique: { gols: 2, assist: 0, ga: 2, mins: 820, jogos: 43, xg: 0.8, xa: 0.5, chancesCriadas: 7, driblesCertos: 15, passesProgressivos: 30, disponibilidade: 55 },
      endrick: createEmptyStats(),
    },
    selecao: {
      neymar: { gols: 8, assist: 4, ga: 12, mins: 870, jogos: 10, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      vini: { gols: 0, assist: 1, ga: 1, mins: 180, jogos: 3, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      raphinha: createEmptyStats(),
      estevao: createEmptyStats(),
      joaopedro: createEmptyStats(),
      rodrygo: createEmptyStats(),
      richarlison: { gols: 5, assist: 2, ga: 7, mins: 800, jogos: 10, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 1, assist: 2, ga: 3, mins: 500, jogos: 8, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: createEmptyStats(),
      cunha: createEmptyStats(),
      thiago: createEmptyStats(),
      paqueta: { gols: 2, assist: 2, ga: 4, mins: 600, jogos: 10, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      henrique: createEmptyStats(),
      endrick: createEmptyStats(),
    },
  },
  {
    year: '2021/22',
    clubes: {
      neymar: { gols: 13, assist: 8, ga: 21, mins: 2300, jogos: 28, xg: 11, xa: 8, chancesCriadas: 75, driblesCertos: 120, passesProgressivos: 220, disponibilidade: 55 },
      vini: { gols: 22, assist: 16, ga: 38, mins: 3900, jogos: 52, xg: 16, xa: 13, chancesCriadas: 90, driblesCertos: 210, passesProgressivos: 310, disponibilidade: 96 },
      raphinha: { gols: 11, assist: 3, ga: 14, mins: 3000, jogos: 36, xg: 9.5, xa: 5, chancesCriadas: 75, driblesCertos: 120, passesProgressivos: 200, disponibilidade: 94 },
      estevao: createEmptyStats(),
      joaopedro: { gols: 4, assist: 1, ga: 5, mins: 1900, jogos: 29, xg: 3.8, xa: 2.0, chancesCriadas: 25, driblesCertos: 25, passesProgressivos: 60, disponibilidade: 85 },
      rodrygo: createEmptyStats(),
      richarlison: { gols: 11, assist: 5, ga: 16, mins: 2500, jogos: 30, xg: 8, xa: 4, chancesCriadas: 35, driblesCertos: 40, passesProgressivos: 95, disponibilidade: 85 },
      jesus: { gols: 13, assist: 12, ga: 25, mins: 2300, jogos: 41, xg: 11, xa: 9, chancesCriadas: 60, driblesCertos: 60, passesProgressivos: 200, disponibilidade: 85 },
      martinelli: { gols: 6, assist: 6, ga: 12, mins: 1900, jogos: 36, xg: 5, xa: 4, chancesCriadas: 35, driblesCertos: 45, passesProgressivos: 110, disponibilidade: 82 },
      cunha: { gols: 7, assist: 3, ga: 10, mins: 2000, jogos: 35, xg: 6, xa: 3, chancesCriadas: 25, driblesCertos: 35, passesProgressivos: 70, disponibilidade: 82 },
      thiago: { gols: 7, assist: 0, ga: 7, mins: 800, jogos: 15, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 50 },
      paqueta: { gols: 11, assist: 6, ga: 17, mins: 3350, jogos: 44, xg: 8, xa: 6, chancesCriadas: 60, driblesCertos: 55, passesProgressivos: 200, disponibilidade: 92 },
      henrique: { gols: 1, assist: 0, ga: 1, mins: 900, jogos: 25, xg: 1.0, xa: 1.2, chancesCriadas: 12, driblesCertos: 18, passesProgressivos: 40, disponibilidade: 50 },
      endrick: createEmptyStats(),
    },
    selecao: {
      neymar: { gols: 7, assist: 3, ga: 10, mins: 700, jogos: 8, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      vini: { gols: 3, assist: 3, ga: 6, mins: 750, jogos: 10, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      raphinha: { gols: 2, assist: 5, ga: 7, mins: 700, jogos: 11, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: createEmptyStats(),
      joaopedro: createEmptyStats(),
      rodrygo: createEmptyStats(),
      richarlison: { gols: 7, assist: 1, ga: 8, mins: 860, jogos: 11, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 3, assist: 1, ga: 4, mins: 750, jogos: 10, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: createEmptyStats(),
      cunha: { gols: 0, assist: 0, ga: 0, mins: 180, jogos: 3, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: createEmptyStats(),
      paqueta: { gols: 4, assist: 3, ga: 7, mins: 1200, jogos: 16, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      henrique: createEmptyStats(),
      endrick: createEmptyStats(),
    },
  },
  {
    year: '2022/23',
    clubes: {
      neymar: { gols: 18, assist: 17, ga: 35, mins: 2100, jogos: 29, xg: 14, xa: 12, chancesCriadas: 95, driblesCertos: 130, passesProgressivos: 240, disponibilidade: 55 },
      vini: { gols: 23, assist: 21, ga: 44, mins: 4100, jogos: 55, xg: 18, xa: 16, chancesCriadas: 105, driblesCertos: 230, passesProgressivos: 330, disponibilidade: 95 },
      raphinha: { gols: 10, assist: 12, ga: 22, mins: 3400, jogos: 50, xg: 8, xa: 9.5, chancesCriadas: 95, driblesCertos: 110, passesProgressivos: 240, disponibilidade: 95 },
      estevao: createEmptyStats(),
      joaopedro: { gols: 11, assist: 4, ga: 15, mins: 2700, jogos: 35, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 95 },
      rodrygo: createEmptyStats(),
      richarlison: { gols: 3, assist: 3, ga: 6, mins: 1900, jogos: 35, xg: 7, xa: 3, chancesCriadas: 30, driblesCertos: 30, passesProgressivos: 80, disponibilidade: 82 },
      jesus: { gols: 11, assist: 6, ga: 17, mins: 2000, jogos: 33, xg: 10, xa: 5, chancesCriadas: 45, driblesCertos: 50, passesProgressivos: 170, disponibilidade: 70 },
      martinelli: { gols: 15, assist: 6, ga: 21, mins: 3200, jogos: 46, xg: 12, xa: 6, chancesCriadas: 60, driblesCertos: 70, passesProgressivos: 190, disponibilidade: 93 },
      cunha: { gols: 4, assist: 0, ga: 4, mins: 1500, jogos: 30, xg: 4, xa: 2, chancesCriadas: 20, driblesCertos: 30, passesProgressivos: 60, disponibilidade: 75 },
      thiago: { gols: 20, assist: 8, ga: 28, mins: 3800, jogos: 52, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 85 },
      paqueta: { gols: 5, assist: 4, ga: 9, mins: 3300, jogos: 41, xg: 3.5, xa: 5, chancesCriadas: 55, driblesCertos: 40, passesProgressivos: 180, disponibilidade: 95 },
      henrique: { gols: 0, assist: 0, ga: 0, mins: 550, jogos: 10, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 50 },
      endrick: { gols: 3, assist: 0, ga: 3, mins: 150, jogos: 7, xg: 1.8, xa: 0.3, chancesCriadas: 5, driblesCertos: 8, passesProgressivos: 15, disponibilidade: 20 },
    },
    selecao: {
      neymar: { gols: 1, assist: 0, ga: 1, mins: 230, jogos: 3, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      vini: { gols: 1, assist: 1, ga: 2, mins: 320, jogos: 4, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      raphinha: { gols: 2, assist: 2, ga: 4, mins: 480, jogos: 6, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: createEmptyStats(),
      joaopedro: createEmptyStats(),
      rodrygo: createEmptyStats(),
      richarlison: { gols: 0, assist: 0, ga: 0, mins: 180, jogos: 3, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 1, assist: 0, ga: 1, mins: 300, jogos: 4, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: { gols: 2, assist: 1, ga: 3, mins: 350, jogos: 6, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 0, assist: 0, ga: 0, mins: 100, jogos: 2, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: createEmptyStats(),
      paqueta: { gols: 2, assist: 2, ga: 4, mins: 550, jogos: 8, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      henrique: createEmptyStats(),
      endrick: createEmptyStats(),
    },
  },
  {
    year: '2023/24',
    clubes: {
      neymar: { gols: 1, assist: 3, ga: 4, mins: 400, jogos: 7, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 12 },
      vini: { gols: 24, assist: 11, ga: 35, mins: 3100, jogos: 39, xg: 19, xa: 9, chancesCriadas: 85, driblesCertos: 180, passesProgressivos: 280, disponibilidade: 78 },
      raphinha: { gols: 10, assist: 11, ga: 21, mins: 2800, jogos: 37, xg: 9, xa: 9, chancesCriadas: 85, driblesCertos: 100, passesProgressivos: 220, disponibilidade: 82 },
      estevao: { gols: 0, assist: 0, ga: 0, mins: 12, jogos: 1, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 1 },
      joaopedro: { gols: 20, assist: 7, ga: 27, mins: 2400, jogos: 40, xg: 7.8, xa: 3.5, chancesCriadas: 40, driblesCertos: 30, passesProgressivos: 70, disponibilidade: 85 },
      rodrygo: createEmptyStats(),
      richarlison: { gols: 12, assist: 2, ga: 14, mins: 1900, jogos: 31, xg: 9, xa: 3, chancesCriadas: 30, driblesCertos: 30, passesProgressivos: 80, disponibilidade: 78 },
      jesus: { gols: 8, assist: 4, ga: 12, mins: 1900, jogos: 36, xg: 9, xa: 5, chancesCriadas: 40, driblesCertos: 40, passesProgressivos: 160, disponibilidade: 80 },
      martinelli: { gols: 8, assist: 5, ga: 13, mins: 2600, jogos: 44, xg: 10, xa: 5, chancesCriadas: 55, driblesCertos: 60, passesProgressivos: 170, disponibilidade: 85 },
      cunha: { gols: 12, assist: 7, ga: 19, mins: 2700, jogos: 32, xg: 11, xa: 6, chancesCriadas: 55, driblesCertos: 70, passesProgressivos: 170, disponibilidade: 90 },
      thiago: { gols: 29, assist: 6, ga: 35, mins: 4500, jogos: 55, xg: 24, xa: 4.5, chancesCriadas: 90, driblesCertos: 30, passesProgressivos: 50, disponibilidade: 95 },
      paqueta: { gols: 8, assist: 6, ga: 14, mins: 3400, jogos: 43, xg: 4.5, xa: 4.2, chancesCriadas: 55, driblesCertos: 45, passesProgressivos: 200, disponibilidade: 90 },
      henrique: { gols: 7, assist: 1, ga: 8, mins: 3000, jogos: 83, xg: 1.5, xa: 1.5, chancesCriadas: 15, driblesCertos: 20, passesProgressivos: 40, disponibilidade: 95 },
      endrick: { gols: 14, assist: 5, ga: 19, mins: 3200, jogos: 53, xg: 11.5, xa: 3.5, chancesCriadas: 90, driblesCertos: 85, passesProgressivos: 80, disponibilidade: 90 },
    },
    selecao: {
      neymar: { gols: 1, assist: 0, ga: 1, mins: 180, jogos: 2, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      vini: { gols: 2, assist: 2, ga: 4, mins: 640, jogos: 8, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      raphinha: { gols: 4, assist: 4, ga: 8, mins: 900, jogos: 11, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: createEmptyStats(),
      joaopedro: { gols: 0, assist: 0, ga: 0, mins: 63, jogos: 1, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      rodrygo: createEmptyStats(),
      richarlison: { gols: 2, assist: 1, ga: 3, mins: 400, jogos: 6, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 0, assist: 0, ga: 0, mins: 150, jogos: 3, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: { gols: 1, assist: 0, ga: 1, mins: 300, jogos: 5, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 0, assist: 0, ga: 0, mins: 250, jogos: 4, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: createEmptyStats(),
      paqueta: { gols: 2, assist: 2, ga: 4, mins: 650, jogos: 10, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      henrique: createEmptyStats(),
      endrick: { gols: 3, assist: 0, ga: 3, mins: 400, jogos: 9, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 80 },
    },
  },
  {
    year: '2024/25',
    clubes: {
      neymar: { gols: 3, assist: 1, ga: 4, mins: 700, jogos: 10, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 25 },
      vini: { gols: 22, assist: 11, ga: 33, mins: 3500, jogos: 43, xg: 18, xa: 10, chancesCriadas: 90, driblesCertos: 180, passesProgressivos: 300, disponibilidade: 87 },
      raphinha: { gols: 34, assist: 22, ga: 56, mins: 4500, jogos: 57, xg: 28, xa: 17, chancesCriadas: 130, driblesCertos: 150, passesProgressivos: 330, disponibilidade: 98 },
      estevao: { gols: 15, assist: 11, ga: 26, mins: 3100, jogos: 45, xg: 10.5, xa: 7, chancesCriadas: 180, driblesCertos: 110, passesProgressivos: 180, disponibilidade: 90 },
      joaopedro: { gols: 10, assist: 6, ga: 16, mins: 2100, jogos: 30, xg: 7, xa: 3.5, chancesCriadas: 37, driblesCertos: 40, passesProgressivos: 70, disponibilidade: 78 },
      rodrygo: createEmptyStats(),
      richarlison: { gols: 5, assist: 0, ga: 5, mins: 1400, jogos: 24, xg: 5, xa: 2, chancesCriadas: 20, driblesCertos: 25, passesProgressivos: 55, disponibilidade: 60 },
      jesus: { gols: 7, assist: 3, ga: 10, mins: 1200, jogos: 27, xg: 7, xa: 3, chancesCriadas: 25, driblesCertos: 25, passesProgressivos: 90, disponibilidade: 55 },
      martinelli: { gols: 10, assist: 8, ga: 18, mins: 3100, jogos: 51, xg: 11, xa: 7, chancesCriadas: 65, driblesCertos: 75, passesProgressivos: 200, disponibilidade: 90 },
      cunha: { gols: 15, assist: 6, ga: 21, mins: 2900, jogos: 33, xg: 14, xa: 5, chancesCriadas: 65, driblesCertos: 80, passesProgressivos: 200, disponibilidade: 95 },
      thiago: { gols: 0, assist: 0, ga: 0, mins: 180, jogos: 8, xg: 1.0, xa: 0.1, chancesCriadas: 3, driblesCertos: 2, passesProgressivos: 5, disponibilidade: 21 },
      paqueta: { gols: 5, assist: 5, ga: 10, mins: 2700, jogos: 36, xg: 3.74, xa: 3.29, chancesCriadas: 36, driblesCertos: 21, passesProgressivos: 150, disponibilidade: 90 },
      henrique: { gols: 9, assist: 7, ga: 16, mins: 2500, jogos: 35, xg: 2.94, xa: 3.6, chancesCriadas: 60, driblesCertos: 40, passesProgressivos: 80, disponibilidade: 92 },
      endrick: { gols: 11, assist: 3, ga: 14, mins: 1300, jogos: 59, xg: 7.5, xa: 1.5, chancesCriadas: 40, driblesCertos: 30, passesProgressivos: 40, disponibilidade: 75 },
    },
    selecao: {
      neymar: createEmptyStats(),
      vini: { gols: 2, assist: 1, ga: 3, mins: 480, jogos: 6, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      raphinha: { gols: 6, assist: 3, ga: 9, mins: 850, jogos: 10, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: { gols: 0, assist: 0, ga: 0, mins: 120, jogos: 4, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 40 },
      joaopedro: { gols: 0, assist: 0, ga: 0, mins: 30, jogos: 1, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      rodrygo: createEmptyStats(),
      richarlison: { gols: 2, assist: 1, ga: 3, mins: 550, jogos: 8, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: createEmptyStats(),
      martinelli: { gols: 0, assist: 0, ga: 0, mins: 240, jogos: 4, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 1, assist: 1, ga: 2, mins: 400, jogos: 6, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: createEmptyStats(),
      paqueta: { gols: 2, assist: 2, ga: 4, mins: 700, jogos: 10, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      henrique: createEmptyStats(),
      endrick: { gols: 0, assist: 0, ga: 0, mins: 150, jogos: 5, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 50 },
    },
  },
  {
    year: '2025/26',
    clubes: {
      neymar: { gols: 6, assist: 3, ga: 9, mins: 1400, jogos: 24, xg: 0, xa: 0, chancesCriadas: 30, driblesCertos: 50, passesProgressivos: 80, disponibilidade: 40 },
      vini: { gols: 18, assist: 13, ga: 31, mins: 5893, jogos: 46, xg: 14, xa: 9, chancesCriadas: 70, driblesCertos: 140, passesProgressivos: 230, disponibilidade: 93 },
      raphinha: { gols: 15, assist: 7, ga: 22, mins: 1900, jogos: 26, xg: 11, xa: 5, chancesCriadas: 50, driblesCertos: 60, passesProgressivos: 150, disponibilidade: 70 },
      estevao: { gols: 19, assist: 9, ga: 28, mins: 4100, jogos: 69, xg: 10.1, xa: 7, chancesCriadas: 130, driblesCertos: 80, passesProgressivos: 140, disponibilidade: 85 },
      joaopedro: { gols: 20, assist: 8, ga: 28, mins: 3400, jogos: 43, xg: 16, xa: 5, chancesCriadas: 34, driblesCertos: 50, passesProgressivos: 120, disponibilidade: 92 },
      rodrygo: createEmptyStats(),
      richarlison: { gols: 8, assist: 3, ga: 11, mins: 1700, jogos: 32, xg: 8, xa: 2, chancesCriadas: 25, driblesCertos: 25, passesProgressivos: 60, disponibilidade: 70 },
      jesus: { gols: 5, assist: 1, ga: 6, mins: 700, jogos: 18, xg: 6, xa: 1.5, chancesCriadas: 15, driblesCertos: 10, passesProgressivos: 45, disponibilidade: 35 },
      martinelli: { gols: 11, assist: 5, ga: 16, mins: 2400, jogos: 35, xg: 9, xa: 4, chancesCriadas: 45, driblesCertos: 55, passesProgressivos: 140, disponibilidade: 90 },
      cunha: { gols: 6, assist: 0, ga: 6, mins: 2000, jogos: 27, xg: 7, xa: 4, chancesCriadas: 40, driblesCertos: 50, passesProgressivos: 130, disponibilidade: 90 },
      thiago: { gols: 21, assist: 1, ga: 22, mins: 2834, jogos: 33, xg: 14.73, xa: 1.17, chancesCriadas: 20, driblesCertos: 15, passesProgressivos: 40, disponibilidade: 90 },
      paqueta: { gols: 5, assist: 4, ga: 9, mins: 2000, jogos: 27, xg: 4, xa: 3, chancesCriadas: 40, driblesCertos: 25, passesProgressivos: 120, disponibilidade: 85 },
      henrique: { gols: 1, assist: 3, ga: 4, mins: 1700, jogos: 32, xg: 1.5, xa: 2.5, chancesCriadas: 25, driblesCertos: 25, passesProgressivos: 45, disponibilidade: 80 },
      endrick: { gols: 7, assist: 6, ga: 13, mins: 1200, jogos: 17, xg: 5.5, xa: 3.0, chancesCriadas: 25, driblesCertos: 20, passesProgressivos: 30, disponibilidade: 40 },
    },
    selecao: {
      neymar: createEmptyStats(),
      vini: { gols: 3, assist: 2, ga: 5, mins: 500, jogos: 6, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      raphinha: { gols: 3, assist: 2, ga: 5, mins: 500, jogos: 6, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: { gols: 5, assist: 2, ga: 7, mins: 450, jogos: 7, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 70 },
      joaopedro: { gols: 0, assist: 0, ga: 0, mins: 200, jogos: 4, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      rodrygo: createEmptyStats(),
      richarlison: { gols: 1, assist: 1, ga: 2, mins: 250, jogos: 4, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: createEmptyStats(),
      martinelli: { gols: 0, assist: 0, ga: 0, mins: 180, jogos: 3, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 0, assist: 0, ga: 0, mins: 280, jogos: 4, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: { gols: 0, assist: 0, ga: 0, mins: 19, jogos: 1, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      paqueta: { gols: 1, assist: 1, ga: 2, mins: 280, jogos: 4, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      henrique: createEmptyStats(),
      endrick: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 1, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 10 },
    },
  },
];

export const matchHistory = [
  {
    id: 1,
    date: 'Julho de 2019',
    opponent: 'Peru e Argentina',
    score: 'Brasil Campeão 3x1 e 2x0',
    importance: 'Máxima, Copa América 2019',
    neymarPlayed: false,
    playedWell: true,
    dataAnalysis: 'Neymar cortado por lesão. Brasil conquistou o título jogando futebol de altíssima eficiência tática. Jesus, Firmino e Everton Cebolinha foram protagonistas. Prova máxima de que o coletivo suplanta o individual.'
  },
  {
    id: 2,
    date: 'Março de 2024',
    opponent: 'Inglaterra',
    score: 'Brasil 1 x 0 Inglaterra',
    importance: 'Alta, Amistoso em Wembley',
    neymarPlayed: false,
    playedWell: true,
    dataAnalysis: 'Brasil dominou taticamente. xG 1.95 vs 0.8 da Inglaterra. Raphinha, Vini Jr e Rodrygo criaram 5 grandes chances. Endrick fez o gol da vitória com personalidade absurda.'
  },
  {
    id: 3,
    date: 'Novembro de 2022',
    opponent: 'Suíça',
    score: 'Brasil 1 x 0 Suíça',
    importance: 'Altíssima, Copa do Mundo, fase de grupos',
    neymarPlayed: false,
    playedWell: true,
    dataAnalysis: 'Neymar saiu lesionado na estreia vs Sérvia. Suíça com xG 0.00, zero chutes no gol. Brasil controlou com precisão e venceu com golaço coletivo do Casemiro.'
  },
  {
    id: 4,
    date: 'Dezembro de 2022',
    opponent: 'Coreia do Sul',
    score: 'Brasil 4 x 1 Coreia do Sul',
    importance: 'Altíssima, Oitavas da Copa do Mundo',
    neymarPlayed: true,
    playedWell: true,
    dataAnalysis: 'Auge do Neymar moderno. Participou de 2 gols nos primeiros 36 minutos. xG Brasil 3.2. O time foi uma máquina nesse jogo específico.'
  },
  {
    id: 5,
    date: 'Outubro de 2023',
    opponent: 'Uruguai',
    score: 'Uruguai 2 x 0 Brasil',
    importance: 'Alta, Eliminatórias Copa 2026',
    neymarPlayed: true,
    playedWell: false,
    dataAnalysis: 'Desastre. Brasil com Neymar titular e zero chutes a gol. Neymar foi substituído. O estilo físico de Bielsa apagou qualquer criação individual.'
  }
];