export const evolutionData = [
  {
    year: '2018',
    clubes: {
      neymar: { gols: 4, assist: 9, ga: 13, mins: 2050, jogos: 31, xg: 5.5, xa: 4.8, chancesCriadas: 35, driblesCertos: 90, passesProgressivos: 100, disponibilidade: 65 },
      vini: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      raphinha: { gols: 6, assist: 6, ga: 12, mins: 2400, jogos: 43, xg: 5, xa: 5, chancesCriadas: 55, driblesCertos: 90, passesProgressivos: 150, disponibilidade: 92 },
      rodrygo: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      richarlison: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      paqueta: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      joaopedro: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      endrick: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 }
    },
    selecao: {
      neymar: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      vini: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      raphinha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      rodrygo: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      richarlison: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      paqueta: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      joaopedro: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      endrick: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 }
    }
  },
  {
    year: '2019',
    clubes: {
      neymar: { gols: 6, assist: 3, ga: 9, mins: 2550, jogos: 38, xg: 7, xa: 3.5, chancesCriadas: 40, driblesCertos: 110, passesProgressivos: 160, disponibilidade: 92 },
      vini: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      raphinha: { gols: 8, assist: 7, ga: 15, mins: 2100, jogos: 32, xg: 6.5, xa: 5.5, chancesCriadas: 50, driblesCertos: 110, passesProgressivos: 160, disponibilidade: 87 },
      rodrygo: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      richarlison: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      paqueta: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      joaopedro: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      endrick: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 }
    },
    selecao: {
      neymar: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      vini: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      raphinha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      rodrygo: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      richarlison: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      paqueta: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      joaopedro: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      endrick: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 }
    }
  },
  {
    year: '2020',
    clubes: {
      neymar: { gols: 6, assist: 4, ga: 10, mins: 2900, jogos: 49, xg: 7, xa: 5, chancesCriadas: 55, driblesCertos: 150, passesProgressivos: 220, disponibilidade: 93 },
      vini: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      raphinha: { gols: 7, assist: 10, ga: 17, mins: 2550, jogos: 32, xg: 7, xa: 7.5, chancesCriadas: 65, driblesCertos: 95, passesProgressivos: 180, disponibilidade: 85 },
      rodrygo: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      richarlison: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      paqueta: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      joaopedro: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      endrick: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 }
    },
    selecao: {
      neymar: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      vini: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      raphinha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      rodrygo: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      richarlison: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      paqueta: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      joaopedro: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      endrick: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 }
    }
  },
  {
    year: '2021',
    clubes: {
      neymar: { gols: 22, assist: 16, ga: 38, mins: 3900, jogos: 52, xg: 16, xa: 13, chancesCriadas: 90, driblesCertos: 210, passesProgressivos: 310, disponibilidade: 96 },
      vini: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      raphinha: { gols: 11, assist: 3, ga: 14, mins: 3000, jogos: 36, xg: 9.5, xa: 5, chancesCriadas: 75, driblesCertos: 120, passesProgressivos: 200, disponibilidade: 94 },
      rodrygo: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      richarlison: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      paqueta: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      joaopedro: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      endrick: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 }
    },
    selecao: {
      neymar: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      vini: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      raphinha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      rodrygo: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      richarlison: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      paqueta: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      joaopedro: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      endrick: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 }
    }
  },
  {
    year: '2022',
    clubes: {
      neymar: { gols: 23, assist: 21, ga: 44, mins: 4100, jogos: 55, xg: 18, xa: 16, chancesCriadas: 105, driblesCertos: 230, passesProgressivos: 330, disponibilidade: 95 },
      vini: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      raphinha: { gols: 10, assist: 12, ga: 22, mins: 3400, jogos: 50, xg: 8, xa: 9.5, chancesCriadas: 95, driblesCertos: 110, passesProgressivos: 240, disponibilidade: 95 },
      rodrygo: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      richarlison: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      paqueta: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      joaopedro: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      endrick: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 }
    },
    selecao: {
      neymar: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      vini: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      raphinha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      rodrygo: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      richarlison: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      paqueta: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      joaopedro: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      endrick: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 }
    }
  },
  {
    year: '2023',
    clubes: {
      neymar: { gols: 24, assist: 11, ga: 35, mins: 3100, jogos: 39, xg: 19, xa: 9, chancesCriadas: 85, driblesCertos: 180, passesProgressivos: 280, disponibilidade: 78 },
      vini: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      raphinha: { gols: 10, assist: 11, ga: 21, mins: 2800, jogos: 37, xg: 9, xa: 9, chancesCriadas: 85, driblesCertos: 100, passesProgressivos: 220, disponibilidade: 82 },
      rodrygo: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      richarlison: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      paqueta: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      joaopedro: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      endrick: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 }
    },
    selecao: {
      neymar: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      vini: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      raphinha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      rodrygo: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      richarlison: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      paqueta: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      joaopedro: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      endrick: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 }
    }
  },
  {
    year: '2024',
    clubes: {
      neymar: { gols: 22, assist: 11, ga: 33, mins: 3500, jogos: 43, xg: 18, xa: 10, chancesCriadas: 90, driblesCertos: 180, passesProgressivos: 300, disponibilidade: 87 },
      vini: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      raphinha: { gols: 34, assist: 22, ga: 56, mins: 4500, jogos: 57, xg: 28, xa: 17, chancesCriadas: 130, driblesCertos: 150, passesProgressivos: 330, disponibilidade: 98 },
      rodrygo: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      richarlison: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      paqueta: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      joaopedro: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      endrick: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 }
    },
    selecao: {
      neymar: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      vini: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      raphinha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      rodrygo: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      richarlison: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      paqueta: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      joaopedro: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      endrick: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 }
    }
  },
  {
    year: '2025/26',
    clubes: {
      neymar: { gols: 18, assist: 13, ga: 31, mins: 5893, jogos: 46, xg: 14, xa: 9, chancesCriadas: 70, driblesCertos: 140, passesProgressivos: 230, disponibilidade: 93 },
      vini: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      raphinha: { gols: 15, assist: 7, ga: 22, mins: 1900, jogos: 26, xg: 11, xa: 5, chancesCriadas: 50, driblesCertos: 60, passesProgressivos: 150, disponibilidade: 70 },
      rodrygo: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      richarlison: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      paqueta: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      joaopedro: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      endrick: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 }
    },
    selecao: {
      neymar: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      vini: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      raphinha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      rodrygo: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      richarlison: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      jesus: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      martinelli: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      cunha: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      paqueta: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      joaopedro: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      estevao: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      thiago: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 },
      endrick: { gols: 0, assist: 0, ga: 0, mins: 0, jogos: 0, xg: 0, xa: 0, chancesCriadas: 0, driblesCertos: 0, passesProgressivos: 0, disponibilidade: 0 }
    }
  },
];
